Repository spartaKotlinTeamSober/wachu_server, pull requests merged in 2024-08, with the labels that each got.

#76 :sparkles: Feat/55 OAuth2
  build.gradle.kts
  src/main/kotlin/sparta/nbcamp/wachu/domain/admin/service/AdminService.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/member/dto/ProfileResponse.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/member/dto/SignUpRequest.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/member/dto/SignUpResponse.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/member/entity/Member.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/member/repository/MemberJpaRepository.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/member/repository/MemberRepository.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/member/repository/MemberRepositoryImpl.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/member/service/MemberService.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/member/service/MemberServiceImpl.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/wine/service/WineServiceImpl.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/redis/common/RedisKeyConst.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/security/SecurityConfig.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/security/oauth/KakaoOAuth2LoginClient.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/security/oauth/NaverOAuth2LoginClient.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/security/oauth/RestClientConfig.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/security/oauth/controller/OAuth2LoginController.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/security/oauth/dto/KakaoOAuthLoginUserInfoResponse.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/security/oauth/dto/KakaoOAuthUserPropertiesResponse.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/security/oauth/dto/NaverOAuthLoginUserInfoResponse.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/security/oauth/dto/NaverOAuthUserResponseResponse.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/security/oauth/dto/NaverTokenResponse.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/security/oauth/dto/OAuthResponse.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/security/oauth/service/OAuth2LoginService.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/swagger/SwaggerConfig.kt
  src/test/kotlin/sparta/nbcamp/wachu/WachuApplicationTests.kt
  src/test/kotlin/sparta/nbcamp/wachu/domain/security/JwtTest.kt
Labels: 기능

#84 :sparkles: WineImage 보여주기 기능 추가
  src/main/kotlin/sparta/nbcamp/wachu/domain/wine/dto/WineResponse.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/wine/entity/WineType.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/wine/service/WineImageGetter.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/wine/service/WineServiceImpl.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/aws/AwsConfig.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/aws/s3/S3FilePath.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/aws/s3/S3Service.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/media/MediaS3Service.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/media/MediaS3ServiceImpl.kt
Labels: 기능

#87 :bug: 멤버 로직 변경에 따른 버그 수정
  .github/ISSUE_TEMPLATE/✨기능-추가-수정.md
  .github/ISSUE_TEMPLATE/🐛버그-리포트.md
  src/main/kotlin/sparta/nbcamp/wachu/domain/member/dto/SignUpRequest.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/member/entity/Member.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/member/service/MemberServiceImpl.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/security/jwt/JwtAuthenticationFilter.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/security/jwt/JwtTokenManager.kt
  src/test/kotlin/sparta/nbcamp/wachu/domain/security/JwtTest.kt
Labels: 버그

#91 :bug: 배포중 발견한 문제 수정
  src/main/kotlin/sparta/nbcamp/wachu/domain/member/emailcode/service/CodeService.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/openai/service/WineEmbeddingService.kt
  src/test/kotlin/sparta/nbcamp/wachu/WachuApplicationTests.kt
Labels: 버그

#95 :sparkles: 빌드 분리와 OAuth 수정, 로그아웃 추가
  .gitignore
  src/main/kotlin/sparta/nbcamp/wachu/domain/member/controller/MemberController.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/security/WebConfig.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/security/oauth/controller/OAuth2LoginController.kt
Labels: 기능

#96 :sparkles: 이메일 비동기 스레드
  src/main/kotlin/sparta/nbcamp/wachu/domain/member/controller/MemberController.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/member/emailcode/config/AsyncConfig.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/member/emailcode/service/CodeService.kt
Labels: 기능

#98 :sparkles: 테스트용 h2 분리
  build.gradle.kts
  src/test/kotlin/sparta/nbcamp/wachu/domain/testH2db/H2DatabaseConnectionTest.kt
  src/test/resources/application-test.yml
Labels: 기능

#102 :sparkles: 리뷰 멀티미디어 response 추가 / 수정
  src/main/kotlin/sparta/nbcamp/wachu/domain/review/controller/v1/ReviewController.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/review/dto/v1/ReviewMultiMediaResponse.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/review/dto/v1/ReviewResponse.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/review/repository/v1/ReviewMultiMediaJpaRepository.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/review/repository/v1/ReviewMultiMediaRepository.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/review/repository/v1/ReviewMultiMediaRepositoryImpl.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/review/repository/v1/ReviewRepository.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/review/repository/v1/ReviewRepositoryImpl.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/review/service/v1/ReviewService.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/review/service/v1/ReviewServiceImpl.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/security/jwt/JwtAuthenticationFilter.kt
Labels: 기능

#105 ✨ Feat/#92 CI/CD설정
  .github/workflows/CD.yml
  .github/workflows/CI.yml
  .gitignore
  Dockerfile
  data/embedding-data.json
  src/main/kotlin/sparta/nbcamp/wachu/domain/member/controller/MemberController.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/member/dto/ProfileResponse.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/member/dto/SignUpResponse.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/member/repository/MemberRepository.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/member/repository/MemberRepositoryImpl.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/member/service/MemberService.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/member/service/MemberServiceImpl.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/pairing/dto/v1/PairingRequest.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/pairing/dto/v1/PairingResponse.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/pairing/service/v1/PairingServiceImpl.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/review/dto/v1/ReviewRequest.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/review/dto/v1/ReviewResponse.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/review/service/v1/ReviewServiceImpl.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/wine/controller/WineController.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/wine/service/WineImageGetter.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/openai/common/utils/WineEmbeddingJsonHandler.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/security/jwt/JwtTokenManager.kt
  src/test/kotlin/sparta/nbcamp/wachu/WachuApplicationTests.kt
  src/test/kotlin/sparta/nbcamp/wachu/domain/pairing/service/PairingServiceTest.kt
  src/test/kotlin/sparta/nbcamp/wachu/domain/review/repository/ReviewMultiMediaTestRepository.kt
  src/test/kotlin/sparta/nbcamp/wachu/domain/review/repository/ReviewTestRepositoryImpl.kt
  src/test/kotlin/sparta/nbcamp/wachu/domain/review/service/ReviewServiceTest.kt
  src/test/kotlin/sparta/nbcamp/wachu/domain/wine/WineDBTest.kt
  src/test/resources/application-test.yml
Labels: 문서, 기능

#103 :sparkles: 회원정보 추가
  src/main/kotlin/sparta/nbcamp/wachu/domain/member/controller/MemberController.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/member/dto/ProfileUpdateRequest.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/member/entity/Member.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/member/service/MemberService.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/member/service/MemberServiceImpl.kt
Labels: 기능

#108 ♻️ #106 와인추천시 전체 조회 성능 개선
  .github/workflows/CI.yml
  src/main/kotlin/sparta/nbcamp/wachu/WachuApplication.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/wine/dto/WineResponse.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/wine/repository/WineRepository.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/wine/repository/WineRepositoryImpl.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/wine/service/WineImageGetter.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/wine/service/WineServiceImpl.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/aws/s3/S3Service.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/batches/s3directory/InMemoryDirectory.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/batches/s3directory/S3DirectoryBatchJob.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/batches/winedata/DataLoadCompleteEvent.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/batches/winedata/InMemoryCache.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/batches/winedata/WineDataBatchJob.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/media/MediaS3Service.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/media/MediaS3ServiceImpl.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/openai/dto/WineDataResponse.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/openai/dto/WineEmbeddingData.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/openai/service/WineEmbeddingService.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/openai/service/WineEventListener.kt
Labels: 기능

#104 :sparkles: 멤버 프로필 데이터 response 에 추가
  src/main/kotlin/sparta/nbcamp/wachu/domain/member/controller/MemberController.kt
Labels: 버그, 기능

#115 ♻️ #114/와인 이미지 매칭 로직 수정
  src/main/kotlin/sparta/nbcamp/wachu/domain/wine/dto/WineResponse.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/wine/service/WineImageGetter.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/batches/s3directory/S3DirectoryBatchJob.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/security/oauth/KakaoOAuth2LoginClient.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/security/oauth/NaverOAuth2LoginClient.kt
  src/test/kotlin/sparta/nbcamp/wachu/domain/pairing/service/PairingServiceTest.kt
  src/test/kotlin/sparta/nbcamp/wachu/domain/review/service/ReviewServiceTest.kt
Labels: 기능

#117 :bug: 회원가입 Request 수정
  src/main/kotlin/sparta/nbcamp/wachu/domain/member/controller/MemberController.kt
Labels: 버그

#118 :sparkles: 개인정보 처리 관련 멤버 수정
  src/main/kotlin/sparta/nbcamp/wachu/domain/member/controller/MemberController.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/member/entity/Member.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/member/repository/MemberRepository.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/member/repository/MemberRepositoryImpl.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/member/service/MemberService.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/member/service/MemberServiceImpl.kt
Labels: 문서, 기능

#120 :sparkles: 와인 추천에 가중치 및 유사도 포함
  src/main/kotlin/sparta/nbcamp/wachu/domain/review/service/v1/ReviewServiceImpl.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/wine/controller/WineController.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/wine/dto/RecommendWineRequest.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/wine/dto/WineRecommendResponse.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/wine/entity/Wine.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/wine/service/WineService.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/wine/service/WineServiceImpl.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/openai/common/utils/WineEmbeddingUtility.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/openai/dto/WineEmbeddingData.kt
  src/main/kotlin/sparta/nbcamp/wachu/infra/openai/service/WineEmbeddingService.kt
Labels: 기능

#124 :bug: 탈퇴한 유저 조회 실패
  src/main/kotlin/sparta/nbcamp/wachu/domain/member/entity/Member.kt
Labels: 버그

#127 :sparkles: FE에 맞춰서 API 양식 수정
  src/main/kotlin/sparta/nbcamp/wachu/domain/common/QueryDslUtils.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/pairing/repository/v1/PairingQueryDslRepository.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/review/model/v1/Review.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/review/repository/v1/ReviewQueryDslRepository.kt
  src/main/kotlin/sparta/nbcamp/wachu/domain/wine/repository/WineQueryDslRepositoryImpl.kt
Labels: 기능
